### ISSUE TITLE
How to set headers for request?

### ISSUE THREAD

**Issue by mfirry** [amrhassan/scala-httpc#25]
Hi,
it's not clear to me how I can set headers params for a request.

Thanks

**Comment by amrhassan** [comment]
I just realized that I never exposed a user API for doing that. I just merged in a change that would allow you to do something like:

```scala
import httpc.all._
import httpc.http.Header

object Sandbox extends App {

  // Description of a PUT request yielding a response
  val command = get("http://httpbin.org/get", headers = List(Header("X-Something", "Some value")))

  // Run the command into an Either[HttpError, Response]
  run(command) match {
    case Left(error) ⇒ println(error)
    case Right(response) ⇒
      println(response.status)
      println(response.text.get)
      println(response.json)
  }
}
```

You'll also find some header names defined on the helper object in `httpc.http.HeaderNames` and even convenience constructors on the `httpc.http.Header` object but they are not at all exhaustive yet.

**Comment by amrhassan** [comment]
I've made it even nicer. You can pass any `(String, String)` as a header, and some header constructors and names are available via importing `httpc.all._`.

```scala
import httpc.all._

object Sandbox extends App {

  // Description of a PUT request yielding a response
  val command = get("http://httpbin.org/get", headers = List(cacheControlNoCache, ("X-Something", "Some value"))

  // Run the command into an Either[HttpError, Response]
  run(command) match {
    case Left(error) ⇒ println(error)
    case Right(response) ⇒
      println(response.status)
      println(response.text.get)
      println(response.json)
  }
}
```

Please re-open the issue if you still have any more questions.

**Comment by mfirry** [comment]
This fixes are still in `0.3.0-SNAPSHOT` right?

**Comment by amrhassan** [comment]
Yes

**Comment by mfirry** [comment]
I'm doing
```
val command = get("https://api.github.com/users/scala-italy", headers = List("User-Agent", "Awesome-Octocat-App"))
```

and I get 
`could not find implicit value for evidence parameter of type httpc.convenient.ToHeader[String]`

**Comment by amrhassan** [comment]
You need to pass `headers` as a `List[(String, String)]`.

Or better yet, use the `userAgent` convenience constructor I just merged in ;)

```scala
val command = get("https://api.github.com/users/scala-italy", headers = List(userAgent("Awesome-Octocat-App"))
```

**Comment by mfirry** [comment]
Great! It [works](https://github.com/mfirry/schlepp/blob/master/src/main/scala/com/example/httpcExample.scala) now.
Thanks.

**Comment by amrhassan** [comment]
Yes

LLAP,
Amr Hassan
